### ISSUE TITLE
Integrate Firebase

### ISSUE THREAD

**Issue by shazomii** [shazomii/Notely#2]

**Comment by shash137** [comment]
I'll integrate firebase for authentication.

**Comment by shazomii** [comment]
Awesome. Looking forward to your pr

**Comment by IzzySoft** [comment]
Keep in mind that Firebase is proprietary – so integrating that would make your app "non-FOSS" and no longer eligible e.g. for listing at F-Droid. But luckily it seems this was abandoned; a notes app should not be bound to a cloud resource for authentication, it should rather work even without a network connection :wink:
