### ISSUE TITLE
Menu option of setting is not visible if there is no notes.

### ISSUE THREAD

**Issue by shash137** [shazomii/Notely#25]
Menu option is hidden when app starts(if there is no notes saved by the user). Options must be present in all the screens. 
Instead of adding Light and Dark theme in the setting menu we can place an icon for it in the action bar, I think that will be much better.

**Comment by shazomii** [comment]
Thanks for your observation @shash137.
I've experimented with your suggestion prior to putting the theme selection in settings. The issue I had with placing the dark mode option in each activity is that the current fragment is recreated each time the theme is changed.

In the case of the EditNoteFragment, it was causing a new note to be saved whenever the theme is applied. 

To fix this, I had to change the save behavior of creating/updating note. There are now lots more bugs that I'm still try to fix.
