### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by shazomii** [shazomii/Notely#5]

**Comment by shash137** [comment]
I would like to work on this.

**Comment by shazomii** [comment]
You can go ahead

**Comment by shash137** [comment]
Heyy @shazomii is email auth is okay or I have to add phone auth to the app

**Comment by shazomii** [comment]
Email should do just fine. I would be adding social login in the nearest future.

**Comment by shash137** [comment]
I have opened PR #26 @shazomii  please review it. Thanks

**Comment by shazomii** [comment]
Awesome. I'll review now. Great job!
